CREATE TABLESPACE BDCARRITOCOMPRAS_DATA DATAFILE '/opt/basedatos/DT_BDCARRITOCOMPRAS.DBF' SIZE 200M;
CREATE TEMPORARY TABLESPACE BDCARRITOCOMPRAS_TEMP TEMPFILE '/opt/basedatos/DT_BDCARRITOCOMPRAS_TMP.DBF' SIZE 200M;
CREATE TABLESPACE BDCARRITOCOMPRAS_INDEX DATAFILE '/opt/basedatos/DT_BDCARRITOCOMPRAS_IDX.DBF' SIZE 200M;

ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER BDCARRITOCOMPRAS IDENTIFIED BY BDCARRITOCOMPRAS DEFAULT TABLESPACE BDCARRITOCOMPRAS_DATA 
TEMPORARY TABLESPACE BDCARRITOCOMPRAS_TEMP QUOTA UNLIMITED ON BDCARRITOCOMPRAS_DATA;

CREATE ROLE PROGRAMADOR;
GRANT CREATE SESSION TO PROGRAMADOR;
GRANT CREATE ANY TABLE TO PROGRAMADOR;
GRANT CREATE ROLE TO PROGRAMADOR;
GRANT CREATE USER TO PROGRAMADOR;
GRANT CREATE VIEW TO PROGRAMADOR;
GRANT CREATE ANY INDEX TO PROGRAMADOR;
GRANT CREATE TRIGGER TO PROGRAMADOR;
GRANT CREATE PROCEDURE TO PROGRAMADOR;
GRANT CREATE SEQUENCE TO PROGRAMADOR;

GRANT PROGRAMADOR TO BDCARRITOCOMPRAS;

GRANT UNLIMITED TABLESPACE TO BDCARRITOCOMPRAS;

-- ecommerce

CREATE TABLESPACE ECOMMERCE_DATA DATAFILE '/opt/basedatos/DT_ECOMMERCE.DBF' SIZE 200M;
CREATE TEMPORARY TABLESPACE ECOMMERCE_TEMP TEMPFILE '/opt/basedatos/DT_ECOMMERCE_TMP.DBF' SIZE 200M;
CREATE TABLESPACE ECOMMERCE_INDEX DATAFILE '/opt/basedatos/DT_ECOMMERCE_IDX.DBF' SIZE 200M;

ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER ECOMMERCE IDENTIFIED BY 12345 DEFAULT TABLESPACE ECOMMERCE_DATA 
TEMPORARY TABLESPACE ECOMMERCE_TEMP QUOTA UNLIMITED ON ECOMMERCE_DATA;

CREATE ROLE PROGRAMADOR;
GRANT CREATE SESSION TO PROGRAMADOR;
GRANT CREATE ANY TABLE TO PROGRAMADOR;
GRANT CREATE ROLE TO PROGRAMADOR;
GRANT CREATE USER TO PROGRAMADOR;
GRANT CREATE VIEW TO PROGRAMADOR;
GRANT CREATE ANY INDEX TO PROGRAMADOR;
GRANT CREATE TRIGGER TO PROGRAMADOR;
GRANT CREATE PROCEDURE TO PROGRAMADOR;
GRANT CREATE SEQUENCE TO PROGRAMADOR;

GRANT PROGRAMADOR TO ECOMMERCE;

GRANT UNLIMITED TABLESPACE TO ECOMMERCE;
