CREATE TABLE producto(
    prod_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    prod_nombre VARCHAR2(255),
    prod_foto VARCHAR2(255),
    prod_descripcion VARCHAR2(255),
    prod_precio BINARY_DOUBLE,
    prod_stock NUMBER,
    CONSTRAINT pk_prod_id PRIMARY KEY(prod_id)
);

-- TABLA USUARIOS
CREATE TABLE usuario(
    us_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    us_dni VARCHAR2(10),
    us_nombres VARCHAR2(255),
    us_apellidos VARCHAR2(255),
    --us_direccion VARCHAR2(255),
    us_email VARCHAR2(255),
    us_password VARCHAR2(255),
    us_rol VARCHAR(50),
    CONSTRAINT pk_us_id PRIMARY KEY(us_id),
    CONSTRAINT us_dni_unique UNIQUE (us_dni),
    CONSTRAINT us_email_unique UNIQUE (us_email)
);

-- TABLA DIRECCION
CREATE TABLE direccion(
    dir_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    dir_direccion VARCHAR2(255),
    /*dir_pais VARCHAR2(10),
    dir_ciudad VARCHAR2(255),
    dir_parroquia VARCHAR2(255),*/
    dir_referencia VARCHAR2(255),
    --dir_codigo_postal VARCHAR2(255),
    dir_telefono VARCHAR2(10),
    dir_usu_id NUMBER,
    CONSTRAINT pk_dir_id PRIMARY KEY(dir_id),
    CONSTRAINT fk_dir_usu_id FOREIGN KEY (dir_usu_id) REFERENCES usuario (us_id),    
    CONSTRAINT direccion_unique UNIQUE (dir_direccion, dir_referencia, dir_telefono, dir_usu_id)
);

-- TABLA PAGOS
CREATE TABLE pago(
    pago_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pago_numero_tarj VARCHAR2(30),
    pago_nombre_tarj VARCHAR2(30),
    pago_mes_venc NUMBER,
    pago_anio_venc NUMBER,
    pago_usu_id NUMBER,
    CONSTRAINT pk_pago_id PRIMARY KEY(pago_id),
    CONSTRAINT fk_pago_usu_id FOREIGN KEY (pago_usu_id) REFERENCES usuario (us_id),
    CONSTRAINT pago_usu_id_unique UNIQUE (pago_usu_id)
);

-- TABLA COMPRAS
CREATE TABLE compra(
    comp_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1000,
    comp_us_id NUMBER,
    comp_pago_id NUMBER,
    comp_fecha VARCHAR2(25),
    comp_subtotal BINARY_DOUBLE,
    comp_iva BINARY_DOUBLE,
    comp_total BINARY_DOUBLE,
    comp_estado NUMBER,
    CONSTRAINT pk_comp_id PRIMARY KEY(comp_id),
    CONSTRAINT fk_comp_us_id FOREIGN KEY (comp_us_id) REFERENCES usuario (us_id),
    CONSTRAINT fk_comp_pago_id FOREIGN KEY (comp_pago_id) REFERENCES pago (pago_id)
);

-- TABLA DETALLE COMPRA
CREATE TABLE detalle_compra(
    det_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1000,
    det_prod_id NUMBER,
    det_comp_id NUMBER,
    det_cantidad NUMBER,
    det_precio_compra BINARY_DOUBLE,
    CONSTRAINT pk_det_id PRIMARY KEY(det_id),
    CONSTRAINT fk_det_prod_id FOREIGN KEY (det_prod_id) REFERENCES producto (prod_id),
    CONSTRAINT fk_det_comp_id FOREIGN KEY (det_comp_id) REFERENCES compra (comp_id)
);
        
-- ESTO ES CON CRYPTO
INSERT INTO USUARIO (us_dni, us_nombres, us_apellidos, us_email, us_password, us_rol)
    VALUES ('ADMIN', 'ADMINISTRADOR', 'ADMINISTRADOR', 'ADMINISTRADOR', 
        'gAAAAABfxsUlsc4sCyf0ULuDHdXzeWUytl3jK_Lp-cq06_hEKWzRHLqp3eeazNm4YhqI3DWe_7Djox7IMpzdb3TXVwBQvfwsEg==', 'ADMINISTRADOR');
        

